on: [push, pull_request]
name: Go

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    # Test and generate coverage report for both modules
    - name: Test and Coverage for ASCII Module
      run: go test -v -coverprofile=ascii_coverage.out ./...
      working-directory: ./asciitoolkit/ascii

    - name: Test and Coverage for Util Module
      run: go test -v -coverprofile=util_coverage.out ./...
      working-directory: ./asciitoolkit/util

    - name: Install gocovmerge
      run: go install github.com/wadey/gocovmerge@latest

    - name: Merge Coverage Reports
      run: |
        ~/go/bin/gocovmerge ascii_coverage.out util_coverage.out > combined_coverage.out
      working-directory: ./asciitoolkit

    - name: Upload Combined Coverage to Coveralls
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: ./asciitoolkit/combined_coverage.out
        github-token: ${{ secrets.GITHUB_TOKEN }}
